### ISSUE TITLE
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

### ISSUE THREAD

**Issue by z3roTo0ne** [EthTx/ethtx#69]
Version:0.3.1
```
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [7] [INFO] Starting gunicorn 20.1.0
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [7] [INFO] Using worker: sync
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [14] [INFO] Booting worker with pid: 14
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [15] [INFO] Booting worker with pid: 15
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [16] [INFO] Booting worker with pid: 16
ethtx_ce_1       | [2021-10-15 13:09:57 +0000] [17] [INFO] Booting worker with pid: 17
ethtx_ce_1       | [2021-10-15 13:09:58 +0000] [14] [ERROR] Exception in worker process
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
ethtx_ce_1       |     worker.init_process()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
ethtx_ce_1       |     self.load_wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ethtx_ce_1       |     self.wsgi = self.app.wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
ethtx_ce_1       |     self.callable = self.load()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ethtx_ce_1       |     return self.load_wsgiapp()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ethtx_ce_1       |     return util.import_app(self.app_uri)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
ethtx_ce_1       |     mod = importlib.import_module(module)
ethtx_ce_1       |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ethtx_ce_1       |     return _bootstrap._gcd_import(name[level:], package, level)
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ethtx_ce_1       |   File "/app/wsgi.py", line 23, in <module>
ethtx_ce_1       |     ethtx_config = EthTxConfig(
ethtx_ce_1       | TypeError: __init__() got an unexpected keyword argument 'mongo_database'
ethtx_ce_1       | [2021-10-15 13:09:58 +0000] [14] [INFO] Worker exiting (pid: 14)
ethtx_ce_1       | [2021-10-15 13:09:58 +0000] [15] [ERROR] Exception in worker process
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
ethtx_ce_1       |     worker.init_process()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
ethtx_ce_1       |     self.load_wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ethtx_ce_1       |     self.wsgi = self.app.wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
ethtx_ce_1       |     self.callable = self.load()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ethtx_ce_1       |     return self.load_wsgiapp()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ethtx_ce_1       |     return util.import_app(self.app_uri)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
ethtx_ce_1       |     mod = importlib.import_module(module)
ethtx_ce_1       |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ethtx_ce_1       |     return _bootstrap._gcd_import(name[level:], package, level)
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ethtx_ce_1       |   File "/app/wsgi.py", line 23, in <module>
ethtx_ce_1       |     ethtx_config = EthTxConfig(
ethtx_ce_1       | TypeError: __init__() got an unexpected keyword argument 'mongo_database'
ethtx_ce_1       | [2021-10-15 13:09:58 +0000] [15] [INFO] Worker exiting (pid: 15)
ethtx_ce_1       | [2021-10-15 13:09:59 +0000] [7] [WARNING] Worker with pid 15 was terminated due to signal 15
ethtx_ce_1       | [2021-10-15 13:09:59 +0000] [16] [ERROR] Exception in worker process
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
ethtx_ce_1       |     worker.init_process()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
ethtx_ce_1       |     self.load_wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ethtx_ce_1       |     self.wsgi = self.app.wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
ethtx_ce_1       |     self.callable = self.load()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ethtx_ce_1       |     return self.load_wsgiapp()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ethtx_ce_1       |     return util.import_app(self.app_uri)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
ethtx_ce_1       |     mod = importlib.import_module(module)
ethtx_ce_1       |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ethtx_ce_1       |     return _bootstrap._gcd_import(name[level:], package, level)
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ethtx_ce_1       |   File "/app/wsgi.py", line 23, in <module>
ethtx_ce_1       |     ethtx_config = EthTxConfig(
ethtx_ce_1       | TypeError: __init__() got an unexpected keyword argument 'mongo_database'
ethtx_ce_1       | [2021-10-15 13:09:59 +0000] [16] [INFO] Worker exiting (pid: 16)
ethtx_ce_1       | [2021-10-15 13:09:59 +0000] [17] [ERROR] Exception in worker process
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
ethtx_ce_1       |     worker.init_process()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
ethtx_ce_1       |     self.load_wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ethtx_ce_1       |     self.wsgi = self.app.wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
ethtx_ce_1       |     self.callable = self.load()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ethtx_ce_1       |     return self.load_wsgiapp()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ethtx_ce_1       |     return util.import_app(self.app_uri)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
ethtx_ce_1       |     mod = importlib.import_module(module)
ethtx_ce_1       |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ethtx_ce_1       |     return _bootstrap._gcd_import(name[level:], package, level)
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ethtx_ce_1       |   File "/app/wsgi.py", line 23, in <module>
ethtx_ce_1       |     ethtx_config = EthTxConfig(
ethtx_ce_1       | TypeError: __init__() got an unexpected keyword argument 'mongo_database'
ethtx_ce_1       | [2021-10-15 13:09:59 +0000] [17] [INFO] Worker exiting (pid: 17)
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
ethtx_ce_1       |     self.sleep()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
ethtx_ce_1       |     ready = select.select([self.PIPE[0]], [], [], 1.0)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
ethtx_ce_1       |     self.reap_workers()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
ethtx_ce_1       |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
ethtx_ce_1       | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
ethtx_ce_1       | 
ethtx_ce_1       | During handling of the above exception, another exception occurred:
ethtx_ce_1       | 
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/bin/gunicorn", line 8, in <module>
ethtx_ce_1       |     sys.exit(run())
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
ethtx_ce_1       |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
ethtx_ce_1       |     super().run()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
ethtx_ce_1       |     Arbiter(self).run()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
ethtx_ce_1       |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
ethtx_ce_1       |     self.stop()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
ethtx_ce_1       |     time.sleep(0.1)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
ethtx_ce_1       |     self.reap_workers()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
ethtx_ce_1       |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
ethtx_ce_1       | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
ethtx_ce_ethtx_ce_1 exited with code 1
```

**Comment by z3roTo0ne** [comment]
I've tried, ethtx_ce latest commit:28ccffb4cca90b4e26ce53a81e61f5d441fd23ec, still have a error.
```
ethtx_ce_1       | [2021-10-16 03:49:46 +0000] [14] [ERROR] Exception in worker process
ethtx_ce_1       | Traceback (most recent call last):
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
ethtx_ce_1       |     worker.init_process()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
ethtx_ce_1       |     self.load_wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ethtx_ce_1       |     self.wsgi = self.app.wsgi()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
ethtx_ce_1       |     self.callable = self.load()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ethtx_ce_1       |     return self.load_wsgiapp()
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ethtx_ce_1       |     return util.import_app(self.app_uri)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
ethtx_ce_1       |     mod = importlib.import_module(module)
ethtx_ce_1       |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ethtx_ce_1       |     return _bootstrap._gcd_import(name[level:], package, level)
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ethtx_ce_1       |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
ethtx_ce_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ethtx_ce_1       |   File "/app/wsgi.py", line 39, in <module>
ethtx_ce_1       |     ethtx = EthTx.initialize(ethtx_config)
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/ethtx/ethtx.py", line 113, in initialize
ethtx_ce_1       |     repository = MongoSemanticsDatabase(db=mongo_client.get_database())
ethtx_ce_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2079, in get_database
ethtx_ce_1       |     raise ConfigurationError('No default database defined')
ethtx_ce_1       | pymongo.errors.ConfigurationError: No default database defined
```

so i try this, it is work:
nano docker-compose.yaml
- MONGO_CONNECTION_STRING=mongodb://mongo/ethtx
